### ISSUE TITLE
swagger docs not showing up after starting the container

### ISSUE THREAD

**Issue by sridhar1982** [leanstacks/spring-boot-fundamentals#3]
I cloned the repository and executed `./gradlew bootRun`. I  browsed through the page [http://localhost:8080/swagger-ui.html](http://localhost:8080/swagger-ui.html) after entering credentials from application.properties.
I get broken page. screenshot attached.

I also tried to browse api-docs endpoint but I get 404.
[http://localhost:8080/v2/api-docs](http://localhost:8080/v2/api-docs )

Thanks

P.S: As always I enjoyed the tutorial. very neatly done. looking forward for more.
![screen shot 2016-08-22 at 9 21 46 am](https://cloud.githubusercontent.com/assets/4313954/17862623/e3cd728c-684a-11e6-989e-74cf22a33c4c.png)

**Comment by mwarman** [comment]
Swagger is not intended to be integrated with the spring-boot-fundamentals GitHub repository.  Swagger Docs IS integrated with the LeanStacks Starter Stack project named skeleton-ws-spring-boot.

If you are looking to use Swagger Docs, please fork the skeleton-ws-spring-boot project, read the readme.md file, and give it a go. https://github.com/leanstacks/skeleton-ws-spring-boot

Thanks. LS
